import type { Metadata } from "next";
import { Roboto, Inter } from "next/font/google";
import "./globals.css";
import '../../styles/global.scss';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  variable: '--font-roboto',
  display: 'swap',
})

const inter = Inter({
  subsets: ['latin'],
  weight: '900', 
  variable: '--font-inter',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
