import type { Metadata } from "next";
import { Roboto, Inter, Roboto_Mono, Montserrat, Poppins, Open_Sans, Playfair_Display } from "next/font/google";
import "aos/dist/aos.css";
import "./globals.css";
import "../../styles/global.scss";
import Header from "@/components/header";
import Footer from "@/components/footer";
import AOSProvider from "./AOSProvider";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '600', '700'], 
  variable: '--font-roboto',
  display: 'swap',
});

const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-roboto-mono',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'],
  weight: '900', 
  variable: '--font-inter',
  display: 'swap',
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: [
    "300", // Light
    "400", // Regular
    "500", // Medium
    "700", // Bold
    "800", // Extra Bold
  ],
  variable: "--font-montserrat",
});

const poppins  = Poppins({
  subsets: ["latin"],
  weight: [
    "300", // Light
    "400", // Regular
    "500", // Medium
    "700", // Bold
    "800", // Extra Bold
  ],
  variable: "--font-poppins",
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], // regular and bold
  variable: '--font-open-sans'
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-playfair"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${inter.variable} ${robotoMono.variable} ${montserrat.variable} ${poppins.variable} ${openSans.variable} ${playfair.variable}`}>
        <Header />
        <AOSProvider>
          {children}
        </AOSProvider>
        <Footer />
      </body>
    </html>
  );
}
